language: node_js
dist: trusty
sudo: false

branches:
  only:
    - master

node_js:
  - "4"
  - "6"
  - "7"

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - pkg-config
      - qt5-default

install:
  - npm install

script:
  - npm run lint && npm test
